### ISSUE TITLE
Update lxd-testenv playbooks to automatically generate SSH public key

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-playbooks#4]
https://docs.ansible.com/ansible/latest/modules/user_module.html

Example:

```yaml
- name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
  user:
    name: jsmith
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
```

Should be easy enough to perform a look against the user running the playbook and use that info to generate a key specific to this set of playbooks (intended for testing purposes). This should reduce the chance that the wrong key is inserted into newly created containers.
